//
// Created by Chris Paulusson on 2020-10-19.
//

#ifndef RAY_TRACER_TYPES_H
#define RAY_TRACER_TYPES_H

enum Material {MIRROR, LAMBERTIAN, LIGHT, TRANSPARENT};
enum RayType {SHADOW, REFLECTION, PRIME, SECONDARY, INSIDE_TRANSPARENT};

#endif //RAY_TRACER_TYPES_H
